# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06c12e7a5f056363bd7f2f06453546ac61d355d69d2e1f43b27d9486b48f15652aa85df02ef047e31112497a69a95a426c2b0d78eed866fae5a1229d011b702c

test:
  secret_key_base: 55af3c89236ffbe510376b28fbdb8a14443fc7fa6f259dfc47628ab5a8af89006bf0041eb6dae2cf56c771934f1ffa5909e9064460a9e3d8755f39fe814316ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
